/* DO NOT EDIT THIS FILE IT IS LOCATED AT /Users/administrator/persistance//private/dev/vinc/vlib/js/include/types/system/colors.js. */ 
vweb.colors=class Colors{
static black="\u001b[30m";
static red="\u001b[31m";
static red_bold="\u001b[31m\u001b[1m";
static green="\u001b[32m";
static yellow="\u001b[33m";
static blue="\u001b[34m";
static magenta="\u001b[35m";
static cyan="\u001b[36m";
static gray="\u001b[37m";
static bold="\u001b[1m";
static italic="\u001b[3m";
static end="\u001b[0m";
static enable(){
Colors.black="\u001b[30m";
Colors.red="\u001b[31m";
Colors.red_bold="\u001b[31m\u001b[1m";
Colors.green="\u001b[32m";
Colors.yellow="\u001b[33m";
Colors.blue="\u001b[34m";
Colors.magenta="\u001b[35m";
Colors.cyan="\u001b[36m";
Colors.gray="\u001b[37m";
Colors.bold="\u001b[1m";
Colors.italic="\u001b[3m";
Colors.end="\u001b[0m";
}
static disable(){
Colors.black="";
Colors.red="";
Colors.red_bold="";
Colors.green="";
Colors.yellow="";
Colors.blue="";
Colors.magenta="";
Colors.cyan="";
Colors.gray="";
Colors.bold="";
Colors.italic="";
Colors.end="";
}
}
vweb.color={
black:(data)=>`${vweb.colors.black}${data}${vweb.colors.end}`,
red:(data)=>`${vweb.colors.red}${data}${vweb.colors.end}`,
red_bold:(data)=>`${vweb.colors.red_bold}${data}${vweb.colors.end}`,
green:(data)=>`${vweb.colors.green}${data}${vweb.colors.end}`,
yellow:(data)=>`${vweb.colors.yellow}${data}${vweb.colors.end}`,
blue:(data)=>`${vweb.colors.blue}${data}${vweb.colors.end}`,
magenta:(data)=>`${vweb.colors.magenta}${data}${vweb.colors.end}`,
cyan:(data)=>`${vweb.colors.cyan}${data}${vweb.colors.end}`,
gray:(data)=>`${vweb.colors.gray}${data}${vweb.colors.end}`,
bold:(data)=>`${vweb.colors.bold}${data}${vweb.colors.end}`,
italic:(data)=>`${vweb.colors.italic}${data}${vweb.colors.end}`,
end:(data)=>`${vweb.colors.end}${data}${vweb.colors.end}`,
}
